PREFIX db: <http://localhost/rdf/ontology/>
PREFIX dbo: <http://um-cds/ontologies/databaseontology/>
PREFIX roo: <http://www.cancerdata.org/roo/>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>


INSERT {

	GRAPH <http://annotation.local/> {
        
     ?tablerow roo:P100061 ?patientID.
        
     ?tablerow roo:P100018 ?gender.
        
     ?tablerow roo:has ?age.
        
     ?tablerow roo:P100022 ?hpv.
        
     db:triplifier_test_HN_Maastricht owl:equivalentClass ncit:C16960.
        
     db:triplifier_test_HN_Maastricht.id owl:equivalentClass ncit:C25364.
        
     db:triplifier_test_HN_Maastricht.biological_sex owl:equivalentClass ncit:C28421.
        
     db:triplifier_test_HN_Maastricht.index_tumour_location owl:equivalentClass ncit:C3263.

     db:triplifier_test_HN_Maastricht.age_at_diagnosis owl:equivalentClass roo:C100003.
        
     db:triplifier_test_HN_Maastricht.performance_status_ecog owl:equivalentClass roo:whostatus.

	db:triplifier_test_HN_Maastricht.overall_hpv_p16_status owl:equivalentClass ncit:C128839.

	db:triplifier_test_HN_Maastricht.clin_t owl:equivalentClass ncit:C48885.

	db:triplifier_test_HN_Maastricht.clin_n owl:equivalentClass ncit:C48884.

	db:triplifier_test_HN_Maastricht.clin_m owl:equivalentClass ncit:C48883.

	db:triplifier_test_HN_Maastricht.ajcc_stage owl:equivalentClass roo:C100052.

	db:triplifier_test_HN_Maastricht.ajcc_stage owl:equivalentClass roo:C100052.

	db:triplifier_test_HN_Maastricht.pretreat_hb_in_mmolperlitre owl:equivalentClass roo:asaScore.

	db:triplifier_test_HN_Maastricht.cancer_surgery_performed owl:equivalentClass ncit:C17173.
        
      db:triplifier_test_HN_Maastricht.chemotherapy_given owl:equivalentClass ncit:C94626.

	db:triplifier_test_HN_Maastricht.radiotherapy_total_treat_time owl:equivalentClass roo:rttotaldays.

	db:triplifier_test_HN_Maastricht.radiotherapy_refgydose_total_highriskgtv owl:equivalentClass roo:graytotaldose.

	db:triplifier_test_HN_Maastricht.radiotherapy_number_fractions_highriskgtv owl:equivalentClass roo:graydoseperfraction.

	db:triplifier_test_HN_Maastricht.event_overall_survival owl:equivalentClass ncit:C25717.

	db:triplifier_test_HN_Maastricht.overall_survival_in_days owl:equivalentClass roo:overallsurvivaldays.

	db:triplifier_test_HN_Maastricht.event_local_recurrence owl:equivalentClass roo:localrecurrence.

	db:triplifier_test_HN_Maastricht.local_recurrence_in_days owl:equivalentClass roo:localrecurrencedays.

	db:triplifier_test_HN_Maastricht.event_locoregional_recurrence owl:equivalentClass roo:regionalrecurrence.

	db:triplifier_test_HN_Maastricht.locoregional_recurrence_in_days owl:equivalentClass roo:regionalrecurrencedays.

	db:triplifier_test_HN_Maastricht.event_distant_metastases owl:equivalentClass ncit:C19151.

	db:triplifier_test_HN_Maastricht.distant_metastases_in_days owl:equivalentClass roo:regionalrecurrencedays.
        
    dbo:has_value owl:sameAs roo:P100042.    #has_value
        
    } 
    
}

WHERE

{
    ?tablerow rdf:type db:triplifier_test_HN_Maastricht.
    
	?tablerow dbo:has_column ?patientID, ?gender.
	
    ?patientID rdf:type db:triplifier_test_HN_Maastricht.id. 
    
    ?gender rdf:type db:triplifier_test_HN_Maastricht.biological_sex.
        
        
      }
       