PREFIX db: <http://localhost/rdf/ontology/>
PREFIX dbo: <http://um-cds/ontologies/databaseontology/>
PREFIX roo: <http://www.cancerdata.org/roo/>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX map: <http://172.20.10.14/rdf/data/triplifier_test_HN_Maastricht/>

INSERT 
    {
    
     GRAPH <http://annotation.local/>
    {
    
     db:triplifier_test_HN_Toronto.years rdf:type owl:Class.  
   
     db:triplifier_test_HN_Toronto.years rdfs:label "Years".
    
     db:triplifier_test_HN_Toronto.days rdf:type owl:Class.
    
     db:triplifier_test_HN_Toronto.days rdfs:label "Days".
    
     db:triplifier_test_HN_Toronto.Gray rdf:type owl:Class. 
  
     db:triplifier_test_HN_Toronto.Gray rdfs:label "Gy".
   
     db:triplifier_test_HN_Toronto.radiotherapyClass rdf:type owl:Class.
    
     db:triplifier_test_HN_Toronto.radiotherapyClass dbo:table db:triplifier_test_HN_Toronto.
    
     db:triplifier_test_HN_Toronto.radiotherapyClass rdfs:label "Radiotherapy".
     
     db:triplifier_test_HN_Toronto.neoplasmClass rdf:type owl:Class. 
     
     db:triplifier_test_HN_Toronto.neoplasmClass dbo:table db:triplifier_test_HN_Toronto.
        
     db:triplifier_test_HN_Toronto.neoplasmClass rdfs:label "Neoplasm".
    
     ?tablerowTor dbo:has_column ?neoplasmTor, ?radiotherapyTor.
     
     ?neoplasmTor rdf:type db:triplifier_test_HN_Toronto.neoplasmClass.
    
     ?radiotherapyTor rdf:type db:triplifier_test_HN_Toronto.radiotherapyClass.
}
  
}

where 
{
    BIND(IRI(CONCAT(str(?tablerowTor), "/neoplasm")) as ?neoplasmTor).
    
    BIND(IRI(CONCAT(str(?tablerowTor), "/radiotherapy")) as ?radiotherapyTor).
    
    ?tablerowTor rdf:type db:triplifier_test_HN_Toronto.
   
}


